################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS/cmsis_os.c \
C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/Middlewares/Third_Party/FreeRTOS/Source/croutine.c \
C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/Middlewares/Third_Party/FreeRTOS/Source/event_groups.c \
C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/Middlewares/Third_Party/FreeRTOS/Source/portable/MemMang/heap_4.c \
C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/Middlewares/Third_Party/FreeRTOS/Source/list.c \
C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F/port.c \
C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/Middlewares/Third_Party/FreeRTOS/Source/queue.c \
C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/Middlewares/Third_Party/FreeRTOS/Source/stream_buffer.c \
C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/Middlewares/Third_Party/FreeRTOS/Source/tasks.c \
C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/Middlewares/Third_Party/FreeRTOS/Source/timers.c 

OBJS += \
./Middlewares/FreeRTOS/cmsis_os.o \
./Middlewares/FreeRTOS/croutine.o \
./Middlewares/FreeRTOS/event_groups.o \
./Middlewares/FreeRTOS/heap_4.o \
./Middlewares/FreeRTOS/list.o \
./Middlewares/FreeRTOS/port.o \
./Middlewares/FreeRTOS/queue.o \
./Middlewares/FreeRTOS/stream_buffer.o \
./Middlewares/FreeRTOS/tasks.o \
./Middlewares/FreeRTOS/timers.o 

C_DEPS += \
./Middlewares/FreeRTOS/cmsis_os.d \
./Middlewares/FreeRTOS/croutine.d \
./Middlewares/FreeRTOS/event_groups.d \
./Middlewares/FreeRTOS/heap_4.d \
./Middlewares/FreeRTOS/list.d \
./Middlewares/FreeRTOS/port.d \
./Middlewares/FreeRTOS/queue.d \
./Middlewares/FreeRTOS/stream_buffer.d \
./Middlewares/FreeRTOS/tasks.d \
./Middlewares/FreeRTOS/timers.d 


# Each subdirectory must supply rules for building sources it contributes
Middlewares/FreeRTOS/cmsis_os.o: C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS/cmsis_os.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 '-D__weak=__attribute__((weak))' '-D__packed=__attribute__((__packed__))' -DUSE_HAL_DRIVER -DSTM32F469xx '-DUSE_BPP=16' -I"C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/Core/Inc" -I"C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/TouchGFX/target" -I"C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/TouchGFX/generated/fonts/include" -I"C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/TouchGFX/generated/texts/include" -I"C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/TouchGFX/generated/images/include" -I"C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/TouchGFX/generated/gui_generated/include" -I"C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/TouchGFX/gui/include" -I"C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/Middlewares/ST/TouchGFX/touchgfx/framework/include" -I"C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/Drivers/STM32F4xx_HAL_Driver/Inc" -I"C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy" -I"C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/Middlewares/Third_Party/FreeRTOS/Source/include" -I"C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS" -I"C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F" -I"C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/Drivers/BSP/Components/exc7200" -I"C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/Drivers/BSP/Components/stmpe811" -I"C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/Drivers/BSP/Components/ts3510" -I"C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/Drivers/BSP/Components/otm8009a" -I"C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/Drivers/BSP/Components/ampire480272" -I"C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/Drivers/BSP/Components/Common" -I"C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/Drivers/CMSIS/Include"  -Og -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Middlewares/FreeRTOS/croutine.o: C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/Middlewares/Third_Party/FreeRTOS/Source/croutine.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 '-D__weak=__attribute__((weak))' '-D__packed=__attribute__((__packed__))' -DUSE_HAL_DRIVER -DSTM32F469xx '-DUSE_BPP=16' -I"C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/Core/Inc" -I"C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/TouchGFX/target" -I"C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/TouchGFX/generated/fonts/include" -I"C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/TouchGFX/generated/texts/include" -I"C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/TouchGFX/generated/images/include" -I"C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/TouchGFX/generated/gui_generated/include" -I"C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/TouchGFX/gui/include" -I"C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/Middlewares/ST/TouchGFX/touchgfx/framework/include" -I"C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/Drivers/STM32F4xx_HAL_Driver/Inc" -I"C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy" -I"C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/Middlewares/Third_Party/FreeRTOS/Source/include" -I"C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS" -I"C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F" -I"C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/Drivers/BSP/Components/exc7200" -I"C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/Drivers/BSP/Components/stmpe811" -I"C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/Drivers/BSP/Components/ts3510" -I"C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/Drivers/BSP/Components/otm8009a" -I"C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/Drivers/BSP/Components/ampire480272" -I"C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/Drivers/BSP/Components/Common" -I"C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/Drivers/CMSIS/Include"  -Og -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Middlewares/FreeRTOS/event_groups.o: C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/Middlewares/Third_Party/FreeRTOS/Source/event_groups.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 '-D__weak=__attribute__((weak))' '-D__packed=__attribute__((__packed__))' -DUSE_HAL_DRIVER -DSTM32F469xx '-DUSE_BPP=16' -I"C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/Core/Inc" -I"C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/TouchGFX/target" -I"C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/TouchGFX/generated/fonts/include" -I"C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/TouchGFX/generated/texts/include" -I"C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/TouchGFX/generated/images/include" -I"C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/TouchGFX/generated/gui_generated/include" -I"C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/TouchGFX/gui/include" -I"C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/Middlewares/ST/TouchGFX/touchgfx/framework/include" -I"C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/Drivers/STM32F4xx_HAL_Driver/Inc" -I"C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy" -I"C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/Middlewares/Third_Party/FreeRTOS/Source/include" -I"C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS" -I"C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F" -I"C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/Drivers/BSP/Components/exc7200" -I"C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/Drivers/BSP/Components/stmpe811" -I"C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/Drivers/BSP/Components/ts3510" -I"C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/Drivers/BSP/Components/otm8009a" -I"C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/Drivers/BSP/Components/ampire480272" -I"C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/Drivers/BSP/Components/Common" -I"C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/Drivers/CMSIS/Include"  -Og -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Middlewares/FreeRTOS/heap_4.o: C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/Middlewares/Third_Party/FreeRTOS/Source/portable/MemMang/heap_4.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 '-D__weak=__attribute__((weak))' '-D__packed=__attribute__((__packed__))' -DUSE_HAL_DRIVER -DSTM32F469xx '-DUSE_BPP=16' -I"C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/Core/Inc" -I"C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/TouchGFX/target" -I"C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/TouchGFX/generated/fonts/include" -I"C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/TouchGFX/generated/texts/include" -I"C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/TouchGFX/generated/images/include" -I"C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/TouchGFX/generated/gui_generated/include" -I"C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/TouchGFX/gui/include" -I"C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/Middlewares/ST/TouchGFX/touchgfx/framework/include" -I"C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/Drivers/STM32F4xx_HAL_Driver/Inc" -I"C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy" -I"C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/Middlewares/Third_Party/FreeRTOS/Source/include" -I"C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS" -I"C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F" -I"C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/Drivers/BSP/Components/exc7200" -I"C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/Drivers/BSP/Components/stmpe811" -I"C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/Drivers/BSP/Components/ts3510" -I"C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/Drivers/BSP/Components/otm8009a" -I"C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/Drivers/BSP/Components/ampire480272" -I"C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/Drivers/BSP/Components/Common" -I"C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/Drivers/CMSIS/Include"  -Og -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Middlewares/FreeRTOS/list.o: C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/Middlewares/Third_Party/FreeRTOS/Source/list.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 '-D__weak=__attribute__((weak))' '-D__packed=__attribute__((__packed__))' -DUSE_HAL_DRIVER -DSTM32F469xx '-DUSE_BPP=16' -I"C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/Core/Inc" -I"C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/TouchGFX/target" -I"C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/TouchGFX/generated/fonts/include" -I"C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/TouchGFX/generated/texts/include" -I"C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/TouchGFX/generated/images/include" -I"C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/TouchGFX/generated/gui_generated/include" -I"C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/TouchGFX/gui/include" -I"C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/Middlewares/ST/TouchGFX/touchgfx/framework/include" -I"C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/Drivers/STM32F4xx_HAL_Driver/Inc" -I"C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy" -I"C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/Middlewares/Third_Party/FreeRTOS/Source/include" -I"C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS" -I"C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F" -I"C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/Drivers/BSP/Components/exc7200" -I"C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/Drivers/BSP/Components/stmpe811" -I"C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/Drivers/BSP/Components/ts3510" -I"C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/Drivers/BSP/Components/otm8009a" -I"C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/Drivers/BSP/Components/ampire480272" -I"C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/Drivers/BSP/Components/Common" -I"C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/Drivers/CMSIS/Include"  -Og -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Middlewares/FreeRTOS/port.o: C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F/port.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 '-D__weak=__attribute__((weak))' '-D__packed=__attribute__((__packed__))' -DUSE_HAL_DRIVER -DSTM32F469xx '-DUSE_BPP=16' -I"C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/Core/Inc" -I"C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/TouchGFX/target" -I"C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/TouchGFX/generated/fonts/include" -I"C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/TouchGFX/generated/texts/include" -I"C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/TouchGFX/generated/images/include" -I"C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/TouchGFX/generated/gui_generated/include" -I"C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/TouchGFX/gui/include" -I"C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/Middlewares/ST/TouchGFX/touchgfx/framework/include" -I"C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/Drivers/STM32F4xx_HAL_Driver/Inc" -I"C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy" -I"C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/Middlewares/Third_Party/FreeRTOS/Source/include" -I"C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS" -I"C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F" -I"C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/Drivers/BSP/Components/exc7200" -I"C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/Drivers/BSP/Components/stmpe811" -I"C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/Drivers/BSP/Components/ts3510" -I"C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/Drivers/BSP/Components/otm8009a" -I"C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/Drivers/BSP/Components/ampire480272" -I"C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/Drivers/BSP/Components/Common" -I"C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/Drivers/CMSIS/Include"  -Og -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Middlewares/FreeRTOS/queue.o: C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/Middlewares/Third_Party/FreeRTOS/Source/queue.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 '-D__weak=__attribute__((weak))' '-D__packed=__attribute__((__packed__))' -DUSE_HAL_DRIVER -DSTM32F469xx '-DUSE_BPP=16' -I"C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/Core/Inc" -I"C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/TouchGFX/target" -I"C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/TouchGFX/generated/fonts/include" -I"C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/TouchGFX/generated/texts/include" -I"C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/TouchGFX/generated/images/include" -I"C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/TouchGFX/generated/gui_generated/include" -I"C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/TouchGFX/gui/include" -I"C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/Middlewares/ST/TouchGFX/touchgfx/framework/include" -I"C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/Drivers/STM32F4xx_HAL_Driver/Inc" -I"C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy" -I"C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/Middlewares/Third_Party/FreeRTOS/Source/include" -I"C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS" -I"C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F" -I"C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/Drivers/BSP/Components/exc7200" -I"C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/Drivers/BSP/Components/stmpe811" -I"C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/Drivers/BSP/Components/ts3510" -I"C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/Drivers/BSP/Components/otm8009a" -I"C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/Drivers/BSP/Components/ampire480272" -I"C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/Drivers/BSP/Components/Common" -I"C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/Drivers/CMSIS/Include"  -Og -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Middlewares/FreeRTOS/stream_buffer.o: C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/Middlewares/Third_Party/FreeRTOS/Source/stream_buffer.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 '-D__weak=__attribute__((weak))' '-D__packed=__attribute__((__packed__))' -DUSE_HAL_DRIVER -DSTM32F469xx '-DUSE_BPP=16' -I"C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/Core/Inc" -I"C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/TouchGFX/target" -I"C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/TouchGFX/generated/fonts/include" -I"C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/TouchGFX/generated/texts/include" -I"C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/TouchGFX/generated/images/include" -I"C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/TouchGFX/generated/gui_generated/include" -I"C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/TouchGFX/gui/include" -I"C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/Middlewares/ST/TouchGFX/touchgfx/framework/include" -I"C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/Drivers/STM32F4xx_HAL_Driver/Inc" -I"C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy" -I"C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/Middlewares/Third_Party/FreeRTOS/Source/include" -I"C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS" -I"C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F" -I"C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/Drivers/BSP/Components/exc7200" -I"C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/Drivers/BSP/Components/stmpe811" -I"C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/Drivers/BSP/Components/ts3510" -I"C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/Drivers/BSP/Components/otm8009a" -I"C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/Drivers/BSP/Components/ampire480272" -I"C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/Drivers/BSP/Components/Common" -I"C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/Drivers/CMSIS/Include"  -Og -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Middlewares/FreeRTOS/tasks.o: C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/Middlewares/Third_Party/FreeRTOS/Source/tasks.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 '-D__weak=__attribute__((weak))' '-D__packed=__attribute__((__packed__))' -DUSE_HAL_DRIVER -DSTM32F469xx '-DUSE_BPP=16' -I"C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/Core/Inc" -I"C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/TouchGFX/target" -I"C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/TouchGFX/generated/fonts/include" -I"C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/TouchGFX/generated/texts/include" -I"C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/TouchGFX/generated/images/include" -I"C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/TouchGFX/generated/gui_generated/include" -I"C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/TouchGFX/gui/include" -I"C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/Middlewares/ST/TouchGFX/touchgfx/framework/include" -I"C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/Drivers/STM32F4xx_HAL_Driver/Inc" -I"C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy" -I"C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/Middlewares/Third_Party/FreeRTOS/Source/include" -I"C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS" -I"C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F" -I"C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/Drivers/BSP/Components/exc7200" -I"C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/Drivers/BSP/Components/stmpe811" -I"C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/Drivers/BSP/Components/ts3510" -I"C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/Drivers/BSP/Components/otm8009a" -I"C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/Drivers/BSP/Components/ampire480272" -I"C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/Drivers/BSP/Components/Common" -I"C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/Drivers/CMSIS/Include"  -Og -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Middlewares/FreeRTOS/timers.o: C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/Middlewares/Third_Party/FreeRTOS/Source/timers.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 '-D__weak=__attribute__((weak))' '-D__packed=__attribute__((__packed__))' -DUSE_HAL_DRIVER -DSTM32F469xx '-DUSE_BPP=16' -I"C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/Core/Inc" -I"C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/TouchGFX/target" -I"C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/TouchGFX/generated/fonts/include" -I"C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/TouchGFX/generated/texts/include" -I"C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/TouchGFX/generated/images/include" -I"C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/TouchGFX/generated/gui_generated/include" -I"C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/TouchGFX/gui/include" -I"C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/Middlewares/ST/TouchGFX/touchgfx/framework/include" -I"C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/Drivers/STM32F4xx_HAL_Driver/Inc" -I"C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy" -I"C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/Middlewares/Third_Party/FreeRTOS/Source/include" -I"C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS" -I"C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F" -I"C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/Drivers/BSP/Components/exc7200" -I"C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/Drivers/BSP/Components/stmpe811" -I"C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/Drivers/BSP/Components/ts3510" -I"C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/Drivers/BSP/Components/otm8009a" -I"C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/Drivers/BSP/Components/ampire480272" -I"C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/Drivers/BSP/Components/Common" -I"C:/GitHub_Projekte/glr-2019c-display-steering-wheel/STM32F469_TouchGFX_v2/Drivers/CMSIS/Include"  -Og -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


